### ISSUE TITLE
Error when start server with npm start

### ISSUE THREAD

**Issue by andrelugomes** [antuane/wartank#2]
$ npm start

> WarTank@1.0.0 start c:\Users\ricardo\workspace\wartank
> node app

{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
HTTP Server run in http://localhost:5001

c:\Users\ricardo\workspace\wartank\node_modules\mongodb\lib\server.js:228
        process.nextTick(function() { throw err; })
                                            ^
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1000:19)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! WarTank@1.0.0 start: `node app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the WarTank@1.0.0 start script 'node app'.
npm ERR! This is most likely a problem with the WarTank package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app
npm ERR! You can get their info via:
npm ERR!     npm owner ls WarTank
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Users\ricardo\workspace\wartank\npm-debug.log

**Comment by andrelugomes** [comment]
Neede to install MongoDB ;)

I got it!
